-- MySQL Script generated by MySQL Workbench
-- Sat Mar  3 11:40:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bootCampJava
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bootCampJava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bootCampJava` DEFAULT CHARACTER SET utf8 ;
USE `bootCampJava` ;

-- -----------------------------------------------------
-- Table `bootCampJava`.`SUPPLIERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootCampJava`.`SUPPLIERS` (
  `idSUPPLIERS` INT NOT NULL,
  `sNAME` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSUPPLIERS`),
  UNIQUE INDEX `idSUPPLIERS_UNIQUE` (`idSUPPLIERS` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootCampJava`.`PARTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootCampJava`.`PARTS` (
  `idPARTS` INT NOT NULL,
  `pNAME` VARCHAR(45) NOT NULL,
  `pCOLOR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPARTS`),
  UNIQUE INDEX `idPARTS_UNIQUE` (`idPARTS` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootCampJava`.`CATALOG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootCampJava`.`CATALOG` (
  `id_suppliers` INT NOT NULL,
  `id_parts` INT NOT NULL,
  `cost` REAL NOT NULL,
  PRIMARY KEY (`id_suppliers`, `id_parts`),
  INDEX `id_parts_idx` (`id_parts` ASC),
  CONSTRAINT `id_suppliers`
    FOREIGN KEY (`id_suppliers`)
    REFERENCES `bootCampJava`.`SUPPLIERS` (`idSUPPLIERS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_parts`
    FOREIGN KEY (`id_parts`)
    REFERENCES `bootCampJava`.`PARTS` (`idPARTS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
